baseURL = "/"
languageCode = "zh-cn"
title = "武斌的博客"
theme = "hugo-cxy-theme"
preserveTaxonomyNames = true
paginate = 8 #frontpage pagination
hasCJKLanguage = true

[outputs]
home = ["HTML", "RSS"]

[params]
  hero_bg = "img/home-bg-road.jpg"
  SEOTitle = "wubin1989的博客 | wubin1989 Blog"
  description = "wubin1989，程序员, 摄影爱好者, 背包客 | 这里是 wubin1989 的博客，边走边看，边读边写。"
  keyword = "wubin1989, wubin1989, wubin1989的网络日志, wubin1989的博客, wubin1989 Blog, 博客, 个人网站, 互联网, Web, Nodejs, Reactjs, SaaS, Golang, 微服务, Microservice"
  slogan = "跨过高山，走过四季，不忘初心，永不言弃"
  brief_info = "全栈工程师/背包客/摄影爱好者"
  info = "常年写reactjs、vuejs、java和golang，专注微服务架构和devops相关，喜欢旅游、爬山、外语"
  avatar = "img/avatar-wubin1989.jpg"      # use absolute URL, seeing it's used in both `/` and `/about/`

  image_404 = "img/404-bg.jpg"
  title_404 = "你来到了没有知识的荒原 :("

  # leancloud storage for page view counter
  page_view_conter = false 
  leancloud_app_id = ""
  leancloud_app_key = ""

  # algolia site search
  algolia_search = false
  algolia_appId = ""
  algolia_indexName = ""
  algolia_apiKey = ""

  # Sidebar settings
  featured_tags = true 
  featured_condition_size = 1 

  # Baidu Analytics
  ba_track_id = ""

  #Enable wechat pay & alipay to allow readers send reward money if they like the articles 
  reward = false 
  # reward_guide = "如果这篇文章对你有用,请随意打赏" 

  friends = false
  bookmarks = false
  about_me = true

  # Include any custom CSS and/or JS files, url or relative to /static folder
  custom_css = []
  custom_js = []

  [params.social]
  rss            = true 
  email          = "328454505@qq.com"
  github         = "https://github.com/wubin1989"
  wechat         = "img/wechat_qrcode.jpg"
  
  [[params.friend_link]]
  title = ""
  href =  ""

  [[params.bookmark_link]]
  title =  "Martin Fowler"
  href =  "https://martinfowler.com"
  [[params.bookmark_link]]
  title = "ServiceMesher"
  href =  "http://www.servicemesher.com"
  [[params.bookmark_link]]
  title =  "Pxhere"
  href = "https://pxhere.com"
  [[params.bookmark_link]]
  title = "unsplash"
  href = "https://unsplash.com"
  
  # [[params.addtional_menus]]
  # title =  "BOOKS"
  # href =  "/top/books/"
  # [[params.addtional_menus]]
  # title =  "ABOUT"
  # href =  "/top/about/"

[outputFormats.Algolia]
baseName = "algolia"
isPlainText = true
mediaType = "application/json"
notAlternative = true

[params.algolia]
vars = ["title", "summary", "date", "publishdate", "expirydate", "permalink"]
params = ["categories", "tags"] 

[taxonomies]
tag = "tags"
category = "categories"
archive = "archives"